fd=["html","css","java scrip","node js","react js"]
print(fd)
fd.append("Angular js")
print(fd)
fd.append("express js")
print(fd)
fd.insert(3,"bootstrap")
print(fd)
fd.insert(1,"Tailwind")
print(fd)
fd.pop()
print(fd)
fd.pop()
print(fd)
fd.pop(3)
print(fd)
fd.remove("html")
print(fd)
fd.index("css")
print(fd)